### ISSUE TITLE
Phpunit测试Yaf Action, __construct时出现core

### ISSUE THREAD

**Issue by lancerhe** [laruence/yaf#213]
做Unit Test 尝试Mock Request, Response, View后，初始化Action出现core
```
    /**
     * @test
     */
    public function category_has_exists() {
        $stubRequest  = $this->getMockBuilder('\Yaf\Request\Http')
                        ->setConstructorArgs(['/article/addcategory/name/News2'])
                        ->getMock();
        \Yaf\Dispatcher::getInstance()->getRouter()->route($stubRequest);
        $stubResponse = $this->getMockBuilder('\Yaf\Response\Http')
                        ->disableOriginalConstructor()
                        ->getMock();
        $stubView     = $this->getMockBuilder('\Yaf\View\Simple')
                        ->disableOriginalConstructor()
                        ->getMock();
        // print_r($stubRequest);print_r($stubResponse);print_r($stubView);exit();
        $Action = new Action_AddCategory($stubRequest, $stubResponse, $stubView);
    }
```
这三个对象打印出来的结果是
```
Mock_Http_aa4dcf82 Object
(
    [__phpunit_invocationMocker:Mock_Http_aa4dcf82:private] =>
    [__phpunit_originalObject:Mock_Http_aa4dcf82:private] =>
    [module] =>
    [controller] => article
    [action] => addcategory
    [method] => Cli
    [params:protected] => Array
        (
            [name] => News2
        )

    [language:protected] =>
    [_exception:protected] =>
    [_base_uri:protected] =>
    [uri:protected] => /article/addcategory/name/News2
    [dispatched:protected] =>
    [routed:protected] => 1
)
Mock_Http_36c466f4 Object
(
    [__phpunit_invocationMocker:Mock_Http_36c466f4:private] =>
    [__phpunit_originalObject:Mock_Http_36c466f4:private] =>
    [_header:protected] =>
    [_body:protected] =>
    [_sendheader:protected] => 1
    [_response_code:protected] => 200
)
Mock_Simple_a459539b Object
(
    [__phpunit_invocationMocker:Mock_Simple_a459539b:private] =>
    [__phpunit_originalObject:Mock_Simple_a459539b:private] =>
    [_tpl_vars:protected] =>
    [_tpl_dir:protected] =>
    [_options:protected] =>
)
```
跑UT的结果就是core，
```
[lancer@Lancer-MacBookPro yaf-phpunit]$ phpunit -c tests/phpunit.xml
PHPUnit 4.7.6 by Sebastian Bergmann and contributors.

Segmentation fault: 11
```
另外问一个问题，为何我Mac下用gdb调试core发现 `no core file handler recognizes format`
```
[lancer@Lancer-MacBookPro yaf-phpunit]$ gdb -c /cores/core.6327
GNU gdb (GDB) 7.9.1
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin14.3.0".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
"/cores/core.6327": no core file handler recognizes format
(gdb)
```

**Comment by laruence** [comment]
估计是你的ulimited -c 限制的太小， 导致没有coredump全部信息，你修改下看看

**Comment by lancerhe** [comment]
现在用Root开启unlimited
```
[root@Lancer-MacBookPro yaf-phpunit]$ ulimit -c unlimited
[root@Lancer-MacBookPro yaf-phpunit]$ ulimit
unlimited
[root@Lancer-MacBookPro yaf-phpunit]$ /usr/local/Cellar/php54/5.4.42/bin/php /usr/local/bin/phpunit.phar -c tests/phpunit.xml
PHPUnit 4.7.6 by Sebastian Bergmann and contributors.

Segmentation fault: 11 (core dumped)
[root@Lancer-MacBookPro yaf-phpunit]$ du -sh /cores/core.6873
504M	/cores/core.6873
```
但是仍然显示`no core file handler recognizes format`
```
[root@Lancer-MacBookPro yaf-phpunit]$ gdb /usr/local/Cellar/php54/5.4.42/bin/php -c /cores/core.6873
GNU gdb (GDB) 7.9.1
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin14.3.0".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/local/Cellar/php54/5.4.42/bin/php...(no debugging symbols found)...done.
"/cores/core.6873": no core file handler recognizes format
```

**Comment by lancerhe** [comment]
@laruence 
我今天使用Centos机子测试，可以用GDB读取，能否帮忙看是什么原因？
```
(gdb) bt
#0  0x00007fc6dbadea2c in memcpy () from /lib64/libc.so.6
#1  0x00000000007ad28d in _estrndup (s=0x3b40248 "`\025\204", length=51977568) at /usr/local/src/php-5.4.44/Zend/zend_alloc.c:2611
#2  0x00000000007ce5bd in _zval_copy_ctor_func (zvalue=0x3d140a0) at /usr/local/src/php-5.4.44/Zend/zend_variables.c:123
#3  0x00000000007f3048 in _zval_copy_ctor (object=0x3d13fe0, member=0x3d13548, value=0x3d140a0, key=<value optimized out>) at /usr/local/src/php-5.4.44/Zend/zend_variables.h:45
#4  zend_std_write_property (object=0x3d13fe0, member=0x3d13548, value=0x3d140a0, key=<value optimized out>) at /usr/local/src/php-5.4.44/Zend/zend_object_handlers.c:573
#5  0x00000000007d1668 in zend_update_property (scope=<value optimized out>, object=0x3d13fe0, name=0x7fc6d20a73ec "_view", name_length=5, value=0x7fc6df275670)
    at /usr/local/src/php-5.4.44/Zend/zend_API.c:3654
#6  0x00007fc6d20997ae in yaf_controller_construct (ce=0x3190930, self=0x3d13fe0, request=0x3d16168, response=0x3d18660, view=0x7fc6df275670, args=<value optimized out>)
    at /usr/local/src/phpext/yaf-2.3.3/yaf_controller.c:226
#7  0x00007fc6d20998de in zim_yaf_controller___construct (ht=<value optimized out>, return_value=0x3d13578, return_value_ptr=<value optimized out>, this_ptr=0x3d13fe0, 
    return_value_used=<value optimized out>) at /usr/local/src/phpext/yaf-2.3.3/yaf_controller.c:257
#8  0x0000000000840faa in zend_do_fcall_common_helper_SPEC (execute_data=<value optimized out>) at /usr/local/src/php-5.4.44/Zend/zend_vm_execute.h:643
#9  0x00000000008353b0 in execute (op_array=0x7fc6d1716f68) at /usr/local/src/php-5.4.44/Zend/zend_vm_execute.h:410
#10 0x00000000007c3544 in zend_call_function (fci=0x7fff75a41850, fci_cache=<value optimized out>) at /usr/local/src/php-5.4.44/Zend/zend_execute_API.c:956
#11 0x000000000065c71a in zim_reflection_method_invokeArgs (ht=<value optimized out>, return_value=0x3d13408, return_value_ptr=<value optimized out>, this_ptr=<value optimized out>, 
    return_value_used=<value optimized out>) at /usr/local/src/php-5.4.44/ext/reflection/php_reflection.c:3015
#12 0x0000000000840faa in zend_do_fcall_common_helper_SPEC (execute_data=<value optimized out>) at /usr/local/src/php-5.4.44/Zend/zend_vm_execute.h:643
#13 0x00000000008353b0 in execute (op_array=0x3b44c78) at /usr/local/src/php-5.4.44/Zend/zend_vm_execute.h:410
#14 0x00000000007cecde in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /usr/local/src/php-5.4.44/Zend/zend.c:1329
#15 0x000000000077492e in php_execute_script (primary_file=0x7fff75a44f10) at /usr/local/src/php-5.4.44/main/main.c:2502
#16 0x00000000008758d3 in do_cli (argc=4, argv=0x7fff75a45318) at /usr/local/src/php-5.4.44/sapi/cli/php_cli.c:989
#17 0x0000000000875fc4 in main (argc=4, argv=0x7fff75a45318) at /usr/local/src/php-5.4.44/sapi/cli/php_cli.c:1365
```

**Comment by laruence** [comment]
我想起来前几天刚刚修复了一个类似问题, 你要不试试github上的最新版本代码?

**Comment by lancerhe** [comment]
可以用最新release yaf-3.0.0测试？还是说要用master？

**Comment by lancerhe** [comment]
@laruence 
我用github最新的代码，还是core，以下是结果：
```
(gdb) bt
#0  0x00007f92c10167cb in memcpy () from /lib64/libc.so.6
#1  0x0000000000787fc9 in php_output_handler_append (handler=0x3ad7b88, context=0x7fffc3218ce0) at /usr/local/src/php-5.4.44/main/output.c:907
#2  php_output_handler_op (handler=0x3ad7b88, context=0x7fffc3218ce0) at /usr/local/src/php-5.4.44/main/output.c:956
#3  0x00000000007887f3 in php_output_op (str=0x0, len=50740576) at /usr/local/src/php-5.4.44/main/output.c:1077
#4  php_output_write (str=0x0, len=50740576) at /usr/local/src/php-5.4.44/main/output.c:269
#5  0x00000000007d09d6 in zend_print_zval_ex (write_func=0x774e20 <php_output_wrapper>, expr=0x7fffc3218d50, indent=<value optimized out>) at /usr/local/src/php-5.4.44/Zend/zend.c:330
#6  0x00000000007d0a42 in zend_print_zval_r_ex (write_func=0x774e20 <php_output_wrapper>, expr=0x3be60a0, indent=8) at /usr/local/src/php-5.4.44/Zend/zend.c:446
#7  0x00000000007d0d0f in print_hash (write_func=0x774e20 <php_output_wrapper>, ht=0x3aff9b8, indent=4, is_object=1 '\001') at /usr/local/src/php-5.4.44/Zend/zend.c:182
#8  0x00000000007d0b63 in zend_print_zval_r_ex (write_func=0x774e20 <php_output_wrapper>, expr=<value optimized out>, indent=0) at /usr/local/src/php-5.4.44/Zend/zend.c:437
#9  0x00000000006e4b48 in zif_print_r (ht=<value optimized out>, return_value=0x3be5578, return_value_ptr=<value optimized out>, this_ptr=<value optimized out>, return_value_used=<value optimized out>)
    at /usr/local/src/php-5.4.44/ext/standard/basic_functions.c:5505
#10 0x0000000000840faa in zend_do_fcall_common_helper_SPEC (execute_data=<value optimized out>) at /usr/local/src/php-5.4.44/Zend/zend_vm_execute.h:643
#11 0x00000000008353b0 in execute (op_array=0x7f92b6c4ef68) at /usr/local/src/php-5.4.44/Zend/zend_vm_execute.h:410
#12 0x00000000007c3544 in zend_call_function (fci=0x7fffc3219140, fci_cache=<value optimized out>) at /usr/local/src/php-5.4.44/Zend/zend_execute_API.c:956
#13 0x000000000065c71a in zim_reflection_method_invokeArgs (ht=<value optimized out>, return_value=0x3be5408, return_value_ptr=<value optimized out>, this_ptr=<value optimized out>, 
    return_value_used=<value optimized out>) at /usr/local/src/php-5.4.44/ext/reflection/php_reflection.c:3015
#14 0x0000000000840faa in zend_do_fcall_common_helper_SPEC (execute_data=<value optimized out>) at /usr/local/src/php-5.4.44/Zend/zend_vm_execute.h:643
#15 0x00000000008353b0 in execute (op_array=0x3a16c78) at /usr/local/src/php-5.4.44/Zend/zend_vm_execute.h:410
#16 0x00000000007cecde in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /usr/local/src/php-5.4.44/Zend/zend.c:1329
#17 0x000000000077492e in php_execute_script (primary_file=0x7fffc321c800) at /usr/local/src/php-5.4.44/main/main.c:2502
#18 0x00000000008758d3 in do_cli (argc=4, argv=0x7fffc321cc08) at /usr/local/src/php-5.4.44/sapi/cli/php_cli.c:989
#19 0x0000000000875fc4 in main (argc=4, argv=0x7fffc321cc08) at /usr/local/src/php-5.4.44/sapi/cli/php_cli.c:1365
```

**Comment by lancerhe** [comment]
上面是我new Action后做print_r($Action) 100% core
若只是new，会一定概率出现core，这时候core的结果：
```
#0  0x0000000000000001 in ?? ()
#1  0x00000000007ce5de in _zval_copy_ctor_func (zvalue=0x1e13790) at /usr/local/src/php-5.4.44/Zend/zend_variables.c:146
#2  0x00000000007f3048 in _zval_copy_ctor (object=0x1e10be8, member=0x1e10af8, value=0x1e13790, key=<value optimized out>) at /usr/local/src/php-5.4.44/Zend/zend_variables.h:45
#3  zend_std_write_property (object=0x1e10be8, member=0x1e10af8, value=0x1e13790, key=<value optimized out>) at /usr/local/src/php-5.4.44/Zend/zend_object_handlers.c:573
#4  0x00000000007d1668 in zend_update_property (scope=<value optimized out>, object=0x1e10be8, name=0x7fb5234cc3ec "_view", name_length=5, value=0x7fb53069a670)
    at /usr/local/src/php-5.4.44/Zend/zend_API.c:3654
#5  0x00007fb5234be7ae in yaf_controller_construct (ce=0x128e930, self=0x1e10be8, request=0x1e134f0, response=0x1e15df0, view=0x7fb53069a670, args=<value optimized out>)
    at /usr/local/src/phpext/yaf-2.3.3/yaf_controller.c:226
#6  0x00007fb5234be8de in zim_yaf_controller___construct (ht=<value optimized out>, return_value=0x1e10b28, return_value_ptr=<value optimized out>, this_ptr=0x1e10be8, 
    return_value_used=<value optimized out>) at /usr/local/src/phpext/yaf-2.3.3/yaf_controller.c:257
#7  0x0000000000840faa in zend_do_fcall_common_helper_SPEC (execute_data=<value optimized out>) at /usr/local/src/php-5.4.44/Zend/zend_vm_execute.h:643
#8  0x00000000008353b0 in execute (op_array=0x7fb522b3bf68) at /usr/local/src/php-5.4.44/Zend/zend_vm_execute.h:410
#9  0x00000000007c3544 in zend_call_function (fci=0x7fff6ad55c30, fci_cache=<value optimized out>) at /usr/local/src/php-5.4.44/Zend/zend_execute_API.c:956
#10 0x000000000065c71a in zim_reflection_method_invokeArgs (ht=<value optimized out>, return_value=0x1e10a98, return_value_ptr=<value optimized out>, this_ptr=<value optimized out>, 
    return_value_used=<value optimized out>) at /usr/local/src/php-5.4.44/ext/reflection/php_reflection.c:3015
#11 0x0000000000840faa in zend_do_fcall_common_helper_SPEC (execute_data=<value optimized out>) at /usr/local/src/php-5.4.44/Zend/zend_vm_execute.h:643
#12 0x00000000008353b0 in execute (op_array=0x1c42ac8) at /usr/local/src/php-5.4.44/Zend/zend_vm_execute.h:410
#13 0x00000000007cecde in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /usr/local/src/php-5.4.44/Zend/zend.c:1329
#14 0x000000000077492e in php_execute_script (primary_file=0x7fff6ad592f0) at /usr/local/src/php-5.4.44/main/main.c:2502
#15 0x00000000008758d3 in do_cli (argc=4, argv=0x7fff6ad596f8) at /usr/local/src/php-5.4.44/sapi/cli/php_cli.c:989
#16 0x0000000000875fc4 in main (argc=4, argv=0x7fff6ad596f8) at /usr/local/src/php-5.4.44/sapi/cli/php_cli.c:1365
```

**Comment by laruence** [comment]
看起来你还是在用yaf-2.3.3的代码啊? 
有简单可重现的代码么?

**Comment by lancerhe** [comment]
@laruence 
sorry. 我是make test... 忘了make install.
我刚重新测试了一下，OX S / Centos 只有在master(2.3.6-dev)正常，2.3.5下出现Core。
按之前的说法应该是在最新的master上修复了类似问题，感谢哈！
