### ISSUE TITLE
yaf 中初始化pdo 出现SIGSEGV

### ISSUE THREAD

**Issue by sunmenghua** [laruence/yaf#269]
在yaf中连接 mysql 初始化 pdo 时出现错误：child 63331 exited on signal 11 (SIGSEGV - core dumped)

php version: 7.0.5

```
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from php...done.

warning: core file may not match specified executable file.
[New LWP 63331]

warning: Error reading shared library list entry at 0x6845c700458b4828

warning: Error reading shared library list entry at 0xcd058d4838458948
Core was generated by `php-fpm: pool www                                                             '.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000007fbf32 in zend_init_compiler_data_structures () at /home/ypzd/下载/php/php-7.0.5/Zend/zend_compile.c:297
297		zend_stack_init(&CG(loop_var_stack), sizeof(zend_loop_var));
(gdb) bt
#0  0x00000000007fbf32 in zend_init_compiler_data_structures () at /home/ypzd/下载/php/php-7.0.5/Zend/zend_compile.c:297
#1  0x00000000008206b3 in zend_string_forget_hash_val (s=0x7f699629110000) at /home/ypzd/下载/php/php-7.0.5/Zend/zend_string.h:92
#2  zend_string_alloc (persistent=1, len=7) at /home/ypzd/下载/php/php-7.0.5/Zend/zend_string.h:132
#3  zend_string_init (persistent=1, len=7, str=<optimized out>) at /home/ypzd/下载/php/php-7.0.5/Zend/zend_string.h:157
#4  zend_startup (utility_functions=<optimized out>, extensions=<optimized out>) at /home/ypzd/下载/php/php-7.0.5/Zend/zend.c:746
#5  0x000000000086cc12 in _zend_handle_numeric_str (idx=0x7ffc4ea1ecf8, length=3, key=0x7ffc4ea1eea8 "\006\024")
    at /home/ypzd/下载/php/php-7.0.5/Zend/zend_hash.h:264
#6  zend_fetch_dimension_address_inner (type=1, dim_type=8795147, dim=0x7ffc4ea1ee60, ht=0x7f6996204450)
    at /home/ypzd/下载/php/php-7.0.5/Zend/zend_execute.c:1568
#7  zend_fetch_dimension_address (type=1, dim_type=<optimized out>, dim=<optimized out>, container=<optimized out>, result=0x7f6996213380)
    at /home/ypzd/下载/php/php-7.0.5/Zend/zend_execute.c:1710
#8  zend_fetch_dimension_address_W (result=0x7f6996213380, container_ptr=<optimized out>, dim=<optimized out>, dim_type=8795147)
    at /home/ypzd/下载/php/php-7.0.5/Zend/zend_execute.c:1797
#9  0x00007f6996203458 in ?? ()
#10 0x00007ffc4ea1ee10 in ?? ()
#11 0x0000000000000001 in ?? ()
#12 0x00007f6996286a80 in ?? ()
#13 0x000000000085d356 in zend_objects_store_put (object=0x1) at /home/ypzd/下载/php/php-7.0.5/Zend/zend_objects_API.c:130
#14 0x00000000022a45c0 in ?? ()
#15 0x0000000000ea58d0 in ?? ()
#16 0x0000000000000000 in ?? ()
```

**Comment by laruence** [comment]
你试着设置export ZEND_DONT_UNLOAD_MODULES=1环境变量 重启PHP, 然后再次试试, 看看能不能把那些缺失的符号的显示出来, 从而确定是什么扩展引起的问题

**Comment by sunmenghua** [comment]
刚找到原因了，是SeasLog导致的
