### ISSUE TITLE
PHP 5.6.13+Yaf 2.3.5 core dump

### ISSUE THREAD

**Issue by giddily** [laruence/yaf#393]
PHP 5.6.13
Yaf 2.3.5
gdb php-fpm -c core.585570
Loaded symbols for /usr/lib64/libevent-1.4.so.2
Core was generated by `php-fpm: pool www               '.
Program terminated with signal 11, Segmentation fault.
#0  zend_mm_remove_from_free_list (heap=<value optimized out>, mm_block=0x4ec01758) at /usr/local/src/php-5.6.13/Zend/zend_alloc.c:815
815                             while (*(cp = &(prev->child[prev->child[1] != NULL])) != NULL) {

(gdb) backtrace
#0  zend_mm_remove_from_free_list (heap=<value optimized out>, mm_block=0x4ec01758) at /usr/local/src/php-5.6.13/Zend/zend_alloc.c:815
#1  0x00000000007bfff3 in _zend_mm_free_int (heap=0x1b422d0, p=0x4ec01740) at /usr/local/src/php-5.6.13/Zend/zend_alloc.c:2105
#2  0x00000000007d8420 in _zval_dtor (zval_ptr=<value optimized out>) at /usr/local/src/php-5.6.13/Zend/zend_variables.h:35
#3  i_zval_ptr_dtor (zval_ptr=<value optimized out>) at /usr/local/src/php-5.6.13/Zend/zend_execute.h:79
#4  _zval_ptr_dtor (zval_ptr=<value optimized out>) at /usr/local/src/php-5.6.13/Zend/zend_execute_API.c:424
#5  0x0000000000776cf1 in php_mysqlnd_result_buffered_zval_free_result_pub (set=0x2664858) at /usr/local/src/php-5.6.13/ext/mysqlnd/mysqlnd_result.c:288
#6  php_mysqlnd_result_buffered_free_result_pub (set=0x2664858) at /usr/local/src/php-5.6.13/ext/mysqlnd/mysqlnd_result.c:330
#7  0x00000000007761e2 in php_mysqlnd_res_free_result_buffers_pub (result=0x25d1438) at /usr/local/src/php-5.6.13/ext/mysqlnd/mysqlnd_result.c:376
#8  0x00000000007761fa in php_mysqlnd_res_free_result_contents_internal_pub (result=0x25d1438) at /usr/local/src/php-5.6.13/ext/mysqlnd/mysqlnd_result.c:392
#9  0x0000000000776230 in php_mysqlnd_res_free_result_internal_pub (result=0x25d1438) at /usr/local/src/php-5.6.13/ext/mysqlnd/mysqlnd_result.c:411
#10 0x000000000077e05d in php_mysqlnd_stmt_free_stmt_result_pub (s=0x2660da0) at /usr/local/src/php-5.6.13/ext/mysqlnd/mysqlnd_ps.c:2109
#11 0x000000000077ef7a in php_mysqlnd_stmt_net_close_priv (s=0x2660da0, implicit=<value optimized out>) at /usr/local/src/php-5.6.13/ext/mysqlnd/mysqlnd_ps.c:2235
#12 0x000000000077de3e in php_mysqlnd_stmt_dtor_pub (s=0x2660da0, implicit=0 '\000') at /usr/local/src/php-5.6.13/ext/mysqlnd/mysqlnd_ps.c:2261
#13 0x000000000061c71f in pdo_mysql_stmt_dtor (stmt=0x26618b0) at /usr/local/src/php-5.6.13/ext/pdo_mysql/mysql_statement.c:63
#14 0x00000000006151fa in free_statement (stmt=0x26618b0) at /usr/local/src/php-5.6.13/ext/pdo/pdo_stmt.c:2367
#15 0x0000000000813c68 in zend_objects_store_free_object_storage (objects=0x10e1e40) at /usr/local/src/php-5.6.13/Zend/zend_objects_API.c:97
#16 0x00000000007daa13 in shutdown_executor () at /usr/local/src/php-5.6.13/Zend/zend_execute_API.c:290
#17 0x00000000007e7c72 in zend_deactivate () at /usr/local/src/php-5.6.13/Zend/zend.c:960
#18 0x00000000007870e2 in php_request_shutdown (dummy=<value optimized out>) at /usr/local/src/php-5.6.13/main/main.c:1883
#19 0x0000000000895539 in main (argc=<value optimized out>, argv=<value optimized out>) at /usr/local/src/php-5.6.13/sapi/fpm/fpm/fpm_main.c:1992
这个系统没有用到mysql查询，求解@laruence

**Comment by motecshine** [comment]
看样子是fpm core dump, 你确定 这组fpm 只有你的程序再用吗？

**Comment by lamphp** [comment]
@motecshine 有道理，不止这一个程序在用，但是core文件只在当前程序下生成。

**Comment by laruence** [comment]
最新版应该解决了
