### ISSUE TITLE
VS2017编译生成php_yaf.dll后运行php官网上的demo报错

### ISSUE THREAD

**Issue by wareon** [laruence/yaf#400]
环境：
windows 10
VS2017
php-7.1.16-nts_x86
yaf3.0.7

**报错内容如下：**
`E:\web\temp\yaf>php cmd.php
PHP Fatal error:  Uncaught Yaf_Exception: Parsing ini file 'E:\web\temp\yaf\conf\application.ini' failed in E:\web\temp\yaf\cmd.php:5
Stack trace:
#0 E:\web\temp\yaf\cmd.php(5): Yaf_Application->__construct('E:\\web\\temp\\yaf...')
#1 {main}

Next Yaf_Exception_StartupError: Initialization of application config failed in E:\web\temp\yaf\cmd.php:5
Stack trace:
#0 E:\web\temp\yaf\cmd.php(5): Yaf_Application->__construct('E:\\web\\temp\\yaf...')
#1 {main}
  thrown in E:\web\temp\yaf\cmd.php on line 5

Fatal error: Uncaught Yaf_Exception: Parsing ini file 'E:\web\temp\yaf\conf\application.ini' failed in E:\web\temp\yaf\cmd.php:5
Stack trace:
#0 E:\web\temp\yaf\cmd.php(5): Yaf_Application->__construct('E:\\web\\temp\\yaf...')
#1 {main}

Next Yaf_Exception_StartupError: Initialization of application config failed in E:\web\temp\yaf\cmd.php:5
Stack trace:
#0 E:\web\temp\yaf\cmd.php(5): Yaf_Application->__construct('E:\\web\\temp\\yaf...')
#1 {main}
  thrown in E:\web\temp\yaf\cmd.php on line 5
`

通过附加进程调试发现
**d:\php\php-7.1.16-src\ext\yaf\configs\yaf_config_ini.c**
文件中**第333行VCWD_FOPEN**没有读取到配置文件内容
`if (VCWD_STAT(ini_file, &sb) == 0) {

			if (S_ISREG(sb.st_mode)) {
				if ((fh.handle.fp = VCWD_FOPEN(ini_file, "r"))) {
					fh.filename = ini_file;
					fh.type = ZEND_HANDLE_FP;
					fh.free_filename = 0;
					fh.opened_path = NULL;
					ZVAL_UNDEF(&YAF_G(active_ini_file_section));
					YAF_G(parsing_flag) = YAF_CONFIG_INI_PARSING_START;
					if (section_name && EXPECTED(Z_TYPE_P(section_name) == IS_STRING && Z_STRLEN_P(section_name))) {
						YAF_G(ini_wanted_section) = section_name;
					} else {
						YAF_G(ini_wanted_section) = NULL;
					}

	 				array_init(&configs);
					if (zend_parse_ini_file(&fh, 0, 0 /* ZEND_INI_SCANNER_NORMAL */,
						   	(zend_ini_parser_cb_t)yaf_config_ini_parser_cb, &configs) == FAILURE
							|| Z_TYPE(configs) != IS_ARRAY) {
						zval_ptr_dtor(&configs);
						yaf_trigger_error(E_ERROR, "Parsing ini file '%s' failed", ini_file);
						return NULL;
					}
				}
			} else {
				yaf_trigger_error(E_ERROR, "Argument is not a valid ini file '%s'", ini_file);
				return NULL;
			}
		} else {
			yaf_trigger_error(E_ERROR, "Unable to find config file '%s'", ini_file);
			return NULL;
		}`

**Comment by wareon** [comment]
自己补上相关配置
----------预处理器定义------------
ZEND_DEBUG=0
PHP_YAF_DEBUG=0
PHP_EXTENSION
WIN32
ZEND_WIN32
_WINDOWS
PHP_WIN32
HAVE_YAF=1
YAF_EXPORTS
YAF_NET_EXPORTS
COMPILE_DL_YAF
HAVE_BUNDLED_PCRE=1
_CRT_SECURE_NO_WARNINGS


ZTS（这一个变量加上是开启线程安全，不加是关闭线程安全）

在config.w32.h文件里加上：
#define PHP_COMPILER_ID "VC14" 

_CRT_SECURE_NO_WARNINGS  不提示进程安全信息
