### ISSUE TITLE
yaf3.0.5 zend_update_property coredump问题

### ISSUE THREAD

**Issue by adanteng** [laruence/yaf#449]
版本
php7.1.10
yaf3.0.5

```
(gdb) bt
#0  0x0000000000926ebe in zend_update_property (scope=scope@entry=0x7f452120afc0, object=object@entry=0x7ffdb15fcf80, name=name@entry=0x7f4516979c68 "_request", name_length=name_length@entry=8,
    value=value@entry=0x7f4521279208) at /home/xxx/compile/gg-build/gg-php/build/php/php-7.1.10/Zend/zend_API.c:3871
#1  0x00007f451696d5fa in yaf_controller_construct (ce=ce@entry=0x7f452120afc0, self=self@entry=0x7ffdb15fcf80, request=request@entry=0x7f4521279208, response=response@entry=0x7f45212160a0,
    view=view@entry=0x7ffdb15fd040, args=args@entry=0x0) at /home/xxx/compile/gg-build/gg-php/build/php-ex/yaf-3.0.5/yaf_controller.c:218
#2  0x00007f451695be1b in yaf_dispatcher_handle (dispatcher=dispatcher@entry=0x7f452127a038, request=request@entry=0x7f4521279208, response=response@entry=0x7f45212160a0, view=view@entry=0x7ffdb15fd040)
    at /home/xxx/compile/gg-build/gg-php/build/php-ex/yaf-3.0.5/yaf_dispatcher.c:555
#3  0x00007f451695d3d8 in yaf_dispatcher_dispatch (dispatcher=0x7f452127a038, response_ptr=response_ptr@entry=0x7f45212160a0)
    at /home/xxx/compile/gg-build/gg-php/build/php-ex/yaf-3.0.5/yaf_dispatcher.c:882
#4  0x00007f4516959756 in zim_yaf_application_run (execute_data=<optimized out>, return_value=0x7f45212160a0) at /home/xxx/compile/gg-build/gg-php/build/php-ex/yaf-3.0.5/yaf_application.c:442
#5  0x00000000009ceb78 in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER () at /home/xxx/compile/gg-build/gg-php/build/php/php-7.1.10/Zend/zend_vm_execute.h:1097
#6  0x000000000096737b in execute_ex (ex=<optimized out>) at /home/xxx/compile/gg-build/gg-php/build/php/php-7.1.10/Zend/zend_vm_execute.h:429
#7  0x00000000009d1554 in zend_execute (op_array=0x7f4521279000, op_array@entry=0x7f4521216030, return_value=return_value@entry=0x0)
    at /home/xxx/compile/gg-build/gg-php/build/php/php-7.1.10/Zend/zend_vm_execute.h:474
#8  0x000000000091c4e0 in zend_execute_scripts (type=type@entry=8, retval=retval@entry=0x0, file_count=file_count@entry=3)
    at /home/xxx/compile/gg-build/gg-php/build/php/php-7.1.10/Zend/zend.c:1480
#9  0x00000000008b1030 in php_execute_script (primary_file=primary_file@entry=0x7ffdb15ff570) at /home/xxx/compile/gg-build/gg-php/build/php/php-7.1.10/main/main.c:2552
#10 0x000000000048199c in main (argc=<optimized out>, argv=<optimized out>) at /home/xxx/compile/gg-build/gg-php/build/php/php-7.1.10/sapi/fpm/fpm/fpm_main.c:1966
```

查到yaf_dispatcher.c的553行
```
object_init_ex(&icontroller, ce);
```
这里icontroller中的obj是空的

**Comment by adanteng** [comment]
最终的结果是因为controller中使用了未定义的常量

**Comment by laruence** [comment]
有测试脚本么，不管怎么说都不该coredump，应该修复
